### ISSUE TITLE
missing data files

### ISSUE THREAD

**Issue by fqzhang42** [chendaniely/pandas_for_everyone#2]
can't find folder tidy-data under data folder, which contains all data files for lesson 7. where can I find these data files ?

**Comment by chendaniely** [comment]
@FuQiangZhang-Alex Sorry for the really late reply. I thought this was my own issue, not an externally created one.

the tidy data files are no longer in a `tidy-data` folder in data, they should be the `billboard.csv`, `pew.csv`, `tb.csv`, `weather.csv`, and `country_timeseries` datasets in the `data` folder

**Comment by revirth** [comment]
can't find 'epi_sim.txt' in chapter 10 😒

**Comment by jaykinghorn** [comment]
I'm having the same issue as revirth. I can't find the epi_sim.txt dataset.

**Comment by chendaniely** [comment]
sorry @revirth @jaykinghorn i missed the original ping.

fixed in 5f41c5734826634b31b7e7c9d93cccba95b6ed68, but you might have to unzip the file first (You can also directly read_csv the zip file, actually.)

**Comment by jaykinghorn** [comment]
I'm also not finding the banklist.csv file from Chapter 11, Datetime Methods. 

I'm really enjoying the book BTW. Great work!

**Comment by jaykinghorn** [comment]
[TSLA.csv.zip](https://github.com/chendaniely/pandas_for_everyone/files/1755721/TSLA.csv.zip)

Sorry, here's another one. The Tesla stock data isn't in the data folder and the data_reader is broken.

```
ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues
```
If you have an alternate means of providing the data, that would be appreciated. Thanks!

Edit: I downloaded the Tesla stock data from Yahoo! Finance back to Jan 1 2010. I've attached it here if it is useful for you. 
[TSLA.csv.zip](https://github.com/chendaniely/pandas_for_everyone/files/1755723/TSLA.csv.zip)

**Comment by chendaniely** [comment]
thanks!
I've added the bank and tesla data in 8b825f9d312cb426c56811a7ab3646f138d94cb2

I guess I need to find a different way to get stock data...
