### ISSUE TITLE
More data missing from repository

### ISSUE THREAD

**Issue by jaykinghorn** [chendaniely/pandas_for_everyone#4]
The acs_ny.csv file is missing as well. 

Also, has the book version gone to print. There are some typos in the previous couple chapters. I'll be happy to point them out if it is still at a stage that you're able to correct them.

**Comment by chendaniely** [comment]
thanks, @jaykinghorn any corrections would be very helpful! Things always end up getting overlooked even after multiple passes with multiple people.

Also, I've added the missing data in 431d61b215c76d39687b5d16805e52b5a9a861d4
